load("//tools:defs.bzl", "go_library")

package(
    default_applicable_licenses = ["//:license"],
    licenses = ["notice"],
)

go_library(
    name = "callbacks",
    srcs = [
        "callback_config.go",
    ],
    visibility = ["//pkg/sentry:internal"],
    imports = [

    ],
    deps = [

    ],
)
