# This workflow should run tests
name: "Run tests"
"on":
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - unlocked
      - auto_merge_enabled
  push:
    branches:
      - master
      - dev
      - 106-solve-dependabot-alerts

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3.5.0
        with:
          go-version: '1.20'
      - id: run_tests
        run: make tests