# This workflow should check if new changes are buildable and runnable
name: "Build & Run tester"
"on":
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - unlocked
      - auto_merge_enabled
  push:
    branches:
      - master
      - dev

jobs:
  generate:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3.5.0
        with:
          go-version: '1.20'
      - id: mkdir
        run: mkdir bin
      - id: build
        run: echo ${{ secrets.PASSWD }} | sudo -S make copy TARGETS=runsc DESTINATION=bin/
      - id: run
        run: ./bin/runsc -strace --rootless --network=host --debug do bash
      - id: exit_from_gvisor
        run: exit